### ISSUE TITLE
Index Sentinel 2 COG Error when  using the datacube dataset config(Indexing Sentinel-2 Cloud-Optimised GeoTIFFs) @alexgleith

### ISSUE THREAD

**Issue by giswt** [opendatacube/datacube-dataset-config#40]
When I  used the command  in the document , I got the errors like this:

--stac --no-sign-request \
> s3://sentinel-cogs/sentinel-s2-l2a-cogs/37/M/CS/2017/10/**/S2A_37MCS_20171016_0_L2A.json s2_l2a

ValueError: Region name is not supplied and default can not be found

stac-to-dc --catalog-href='https://earth-search.aws.element84.com/v0/' --bbox='25,20,35,30' --collections='sentinel-s2-l2a-cogs'  --datetime='2020-01-01/2020-01-31'

pystac_client.warnings.DoesNotConformTo: Server does not conform to ITEM_SEARCH, There is not fallback option available for search.

@alexgleith

Open Data Cube core, version 1.8.16.dev22+g584db42c

**Comment by alexgleith** [comment]
try using the newer search endpoint, this one `https://earth-search.aws.element84.com/v1/`

Your first error is different, and you need to set your AWS_DEFAULT_REGION environment variable.

**Comment by giswt** [comment]
> try using the newer search endpoint, this one `https://earth-search.aws.element84.com/v1/`
> 
> Your first error is different, and you need to set your AWS_DEFAULT_REGION environment variable.

Thank you very much  Alex!
