### ISSUE TITLE
Clarification 

### ISSUE THREAD

**Issue by GavinBrelstaff** [opendatacube/datacube-dataset-config#6]
Does the presence of `common.py` in `datacube-dataset-config/blob/master/scripts` indicate a change away from standalone ingestion scripts?

I was intending to contribute scripts for ingesting Sentinel-2 L2A data for  `PRODUCT_TYPE` of  original `S2MSI2Ap` and current `S2MSI2A`.

So I'd appreciate a statement on this.
BTW I think extracting commonalities will help maintainability.

Plus it would be useful to establish test cases for validating such scripts.
For example the L1C script outputs contain spectral band profiles which are not embedded in the L2A data.

**Comment by woodcockr** [comment]
Great question @GavinBrelstaff. 

I've been "collecting" these scripts from various developers across our part of the community and there are minor variations in what appear to be common functions. Sometime its not clear if these are performing the intended function in a different way or just plain getting it wrong (and propagating the error when used as a template).

As you say "extracting commonalities will help maintainability".

It would also be good to remove old scripts that are no longer needed/current from the datacube-core repository or consolidate datacube-dataset-config. It's all a bit confusing at the moment.

Thanks for raising the question, I can't provide an answer but look forward to seeing one develop.

**Comment by alexgleith** [comment]
Although I don't have an answer to the original question, I'm going to close this issue as it hasn't had any input in a long time. Please feel free to reopen if it's still important.
